apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-stage
data:
  USER: root
  # PASSWORD: root
  DATABASE_URL: mysql://192.168.13.28:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
