- hosts:
  - ec2-k8s-m2
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes master"
      shell: kubeadm join k8s-haproxy:6443 --token csvl19.fh6vbi2hyyvml3cx  --discovery-token-ca-cert-hash sha256:111285707e85c7e68bfb8856f7a89104a712c8537805cb26afc5c443c548f30b  --control-plane --certificate-key d37b5f97dc4ce5f3e78dec18e0e30d7e5fc3a2538fa5dad07b295db9e6570296

    - name: "Colocando no path da maquina o conf do kubernetes"
      shell: mkdir -p /root/.kube && sudo cp -f /etc/kubernetes/admin.conf /root/.kube/config && sudo chown 0:0 /root/.kube/config && export KUBECONFIG=/etc/kubernetes/admin.conf
#---
- hosts:
  - ec2-k8s-w1
  - ec2-k8s-w2
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes worker"
      shell: kubeadm join k8s-haproxy:6443 --token csvl19.fh6vbi2hyyvml3cx  --discovery-token-ca-cert-hash sha256:111285707e85c7e68bfb8856f7a89104a712c8537805cb26afc5c443c548f30b 

#---
- hosts:
  - ec2-k8s-m1
  become: yes
  tasks:
    - name: "Configura weavenet para reconhecer os nós master e workers"
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: Espera 30 segundos
      wait_for: timeout=30

    - shell: kubectl get nodes -o wide
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
